### ISSUE TITLE
python 3.5

### ISSUE THREAD

**Issue by Guest007** [AlexandreProenca/django-drf-file-generator#1]
Hi
Unfortunately, can't use it with python 3.5 
Try to fix import error (configparser instead of ConfigParser), but got errors about byte strings...

```
$ drf_gen 
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/proj/bin/drf_gen", line 11, in <module>
    sys.exit(main())
  File "/home/user/.pyenv/versions/proj/lib/python3.5/site-packages/drf_gen/drf_gen.py", line 29, in main
    config.readfp(resource_stream('drf_gen','config.ini'))
  File "/home/user/.pyenv/versions/3.5.0/lib/python3.5/configparser.py", line 761, in readfp
    self.read_file(fp, source=filename)
  File "/home/user/.pyenv/versions/3.5.0/lib/python3.5/configparser.py", line 716, in read_file
    self._read(f, source)
  File "/home/user/.pyenv/versions/3.5.0/lib/python3.5/configparser.py", line 1029, in _read
    if line.strip().startswith(prefix):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by AlexandreProenca** [comment]
Hi friend,
Thank you for report this issue, I will to do this fix on this weekend. if you solve until there, feel free to submit a pull request.
